# Reference: https://www.youtube.com/watch?v=hRSlKRvYe1A
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
    app: helm-app-python
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}
