---
- name: Install docker
  hosts: all
  roles:
    - role: docker
      become: true

- name: Deploying Go web app
  hosts: all
  roles: 
  - role: web_app # non-reusable role
    become: true
    vars:
      web_app_name: "app_go"
      web_app_port: 8080
      web_app_dir: "/home/{{ ansible_user }}/{{ web_app_name }}"
      host_name: "{{ ansible_host }}"
      web_app_full_wipe: true